// WebContainer project templates

export interface WebContainerTemplate {
  name: string;
  description: string;
  files: Record<string, { file: { contents: string } } | { directory: Record<string, unknown> }>;
}

export const createBasicExpressTemplate = (): WebContainerTemplate => ({
  name: "Basic Express App (TypeScript)",
  description: "A simple Express.js application with TypeScript and ESLint",
  files: {
    'package.json': {
      file: {
        contents: JSON.stringify({
          name: "zapdev-express-app",
          version: "1.0.0",
          description: "Express app generated by ZapDev",
          main: "dist/index.js",
          scripts: {
            start: "node dist/index.js",
            dev: "ts-node src/index.ts",
            build: "tsc",
            lint: "eslint src/**/*.ts",
            "lint:fix": "eslint src/**/*.ts --fix"
          },
          dependencies: {
            "express": "^4.18.2"
          },
          devDependencies: {
            "@types/express": "^4.17.17",
            "@types/node": "^20.0.0",
            "@typescript-eslint/eslint-plugin": "^6.0.0",
            "@typescript-eslint/parser": "^6.0.0",
            "eslint": "^8.44.0",
            "ts-node": "^10.9.1",
            "typescript": "^5.1.0"
          }
        }, null, 2)
      }
    },
    'tsconfig.json': {
      file: {
        contents: JSON.stringify({
          compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            outDir: "./dist",
            rootDir: "./src",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true
          },
          include: ["src/**/*"],
          exclude: ["node_modules", "dist"]
        }, null, 2)
      }
    },
    '.eslintrc.json': {
      file: {
        contents: JSON.stringify({
          parser: "@typescript-eslint/parser",
          extends: [
            "eslint:recommended",
            "@typescript-eslint/recommended"
          ],
          plugins: ["@typescript-eslint"],
          rules: {
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-unused-vars": "error",
            "prefer-const": "error"
          },
          env: {
            node: true,
            es2020: true
          }
        }, null, 2)
      }
    },
    'src': {
      directory: {
        'index.ts': {
          file: {
            contents: `import express from 'express';
import path from 'path';

const app = express();
const PORT = 3111;

// Serve static files from public directory
app.use(express.static('public'));

// Basic route
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../public', 'index.html'));
});

// API route example
app.get('/api/hello', (req, res) => {
  res.json({ message: 'Hello from ZapDev TypeScript Express server!' });
});

app.listen(PORT, () => {
  console.log(\`Server running at http://localhost:\${PORT}\`);
});`
            }
          }
        }
      }
    },
    'public': {
      directory: {
        'index.html': {
          file: {
            contents: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZapDev Express App</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .container {
            background: white;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            text-align: center;
            max-width: 500px;
            width: 90%;
        }
        
        h1 {
            color: #333;
            margin-bottom: 1rem;
            font-size: 2.5rem;
        }
        
        p {
            color: #666;
            margin-bottom: 2rem;
            font-size: 1.1rem;
        }
        
        .btn {
            background: #667eea;
            color: white;
            padding: 12px 24px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 1rem;
            transition: background 0.3s;
        }
        
        .btn:hover {
            background: #5a6fd8;
        }
        
        .api-result {
            margin-top: 1rem;
            padding: 1rem;
            background: #f8f9fa;
            border-radius: 5px;
            border-left: 4px solid #667eea;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 ZapDev TypeScript Express</h1>
        <p>Your TypeScript Express.js application is running successfully!</p>
        <button class="btn" onclick="testAPI()">Test API</button>
        <div id="api-result" class="api-result" style="display: none;"></div>
    </div>

    <script>
        async function testAPI() {
            try {
                const response = await fetch('/api/hello');
                const data = await response.json();
                const resultDiv = document.getElementById('api-result');
                resultDiv.innerHTML = \`<strong>API Response:</strong> \${data.message}\`;
                resultDiv.style.display = 'block';
            } catch (error) {
                console.error('Error:', error);
            }
        }
    </script>
</body>
</html>`
          }
        }
      }
    }
  }
});

export const createLandingPageTemplate = (): WebContainerTemplate => ({
  name: "Landing Page Template (TypeScript)",
  description: "A modern landing page with TypeScript, ESLint, and modern tooling",
  files: {
    'package.json': {
      file: {
        contents: JSON.stringify({
          name: "zapdev-landing-page",
          version: "1.0.0",
          description: "Landing page generated by ZapDev",
          main: "dist/index.js",
          scripts: {
            start: "node dist/index.js",
            dev: "ts-node src/index.ts",
            build: "tsc",
            lint: "eslint src/**/*.ts",
            "lint:fix": "eslint src/**/*.ts --fix"
          },
          dependencies: {
            "express": "^4.18.2"
          },
          devDependencies: {
            "@types/express": "^4.17.17",
            "@types/node": "^20.0.0",
            "@typescript-eslint/eslint-plugin": "^6.0.0",
            "@typescript-eslint/parser": "^6.0.0",
            "eslint": "^8.44.0",
            "ts-node": "^10.9.1",
            "typescript": "^5.1.0"
          }
        }, null, 2)
      }
    },
    'tsconfig.json': {
      file: {
        contents: JSON.stringify({
          compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            outDir: "./dist",
            rootDir: "./src",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true
          },
          include: ["src/**/*"],
          exclude: ["node_modules", "dist"]
        }, null, 2)
      }
    },
    '.eslintrc.json': {
      file: {
        contents: JSON.stringify({
          parser: "@typescript-eslint/parser",
          extends: [
            "eslint:recommended",
            "@typescript-eslint/recommended"
          ],
          plugins: ["@typescript-eslint"],
          rules: {
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-unused-vars": "error",
            "prefer-const": "error"
          },
          env: {
            node: true,
            es2020: true
          }
        }, null, 2)
      }
    },
    'src': {
      directory: {
        'index.ts': {
          file: {
            contents: `import express from 'express';
import path from 'path';

const app = express();
const PORT = 3111;

app.use(express.static('public'));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(\`TypeScript Landing page server running at http://localhost:\${PORT}\`);
});`
            }
          }
        }
      }
    },
    'public': {
      directory: {
        'index.html': {
          file: {
            contents: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZapDev Landing Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        
        .hero {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-align: center;
            padding: 100px 20px;
        }
        
        .hero h1 {
            font-size: 3.5rem;
            margin-bottom: 1rem;
            font-weight: 700;
        }
        
        .hero p {
            font-size: 1.25rem;
            margin-bottom: 2rem;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }
        
        .btn {
            background: white;
            color: #667eea;
            padding: 15px 30px;
            border: none;
            border-radius: 50px;
            font-size: 1.1rem;
            font-weight: 600;
            cursor: pointer;
            transition: transform 0.3s, box-shadow 0.3s;
        }
        
        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px rgba(0,0,0,0.2);
        }
        
        .features {
            padding: 80px 20px;
            background: #f8f9fa;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        
        .features h2 {
            text-align: center;
            font-size: 2.5rem;
            margin-bottom: 3rem;
            color: #333;
        }
        
        .features-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }
        
        .feature-card {
            background: white;
            padding: 2rem;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.3s;
        }
        
        .feature-card:hover {
            transform: translateY(-5px);
        }
        
        .feature-icon {
            font-size: 3rem;
            margin-bottom: 1rem;
        }
        
        .feature-card h3 {
            font-size: 1.5rem;
            margin-bottom: 1rem;
            color: #333;
        }
        
        .feature-card p {
            color: #666;
        }
        
        .cta {
            background: #333;
            color: white;
            text-align: center;
            padding: 80px 20px;
        }
        
        .cta h2 {
            font-size: 2.5rem;
            margin-bottom: 1rem;
        }
        
        .cta p {
            font-size: 1.25rem;
            margin-bottom: 2rem;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }
        
        .btn-secondary {
            background: #667eea;
            color: white;
            padding: 15px 30px;
            border: none;
            border-radius: 50px;
            font-size: 1.1rem;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.3s;
        }
        
        .btn-secondary:hover {
            background: #5a6fd8;
        }
    </style>
</head>
<body>
    <section class="hero">
        <div class="container">
            <h1>Welcome to the Future</h1>
            <p>Experience the next generation of web applications built with cutting-edge technology</p>
            <button class="btn">Get Started Today</button>
        </div>
    </section>

    <section class="features">
        <div class="container">
            <h2>Amazing Features</h2>
            <div class="features-grid">
                <div class="feature-card">
                    <div class="feature-icon">⚡</div>
                    <h3>Lightning Fast</h3>
                    <p>Built with modern web technologies for optimal performance and speed</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">🎨</div>
                    <h3>Beautiful Design</h3>
                    <p>Carefully crafted with attention to every detail and user experience</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">🚀</div>
                    <h3>Easy to Deploy</h3>
                    <p>Deploy anywhere with our optimized build process and modern tooling</p>
                </div>
            </div>
        </div>
    </section>

    <section class="cta">
        <div class="container">
            <h2>Ready to Get Started?</h2>
            <p>Join thousands of users who are already building amazing things</p>
            <button class="btn-secondary">Start Building Now</button>
        </div>
    </section>
</body>
</html>`
          }
        }
      }
    }
  }
});

export const createNextJsTemplate = (): WebContainerTemplate => ({
  name: "Next.js App (TypeScript + Tailwind)",
  description: "A modern Next.js application with TypeScript, Tailwind CSS, and animations",
  files: {
    'package.json': {
      file: {
        contents: JSON.stringify({
          name: "zapdev-nextjs-app",
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
          },
          dependencies: {
            "next": "14.0.4",
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "framer-motion": "^10.16.16",
            "lucide-react": "^0.294.0",
            "clsx": "^2.0.0",
            "tailwind-merge": "^2.2.0"
          },
          devDependencies: {
            "@types/node": "^20.10.5",
            "@types/react": "^18.2.45",
            "@types/react-dom": "^18.2.18",
            "autoprefixer": "^10.4.16",
            "eslint": "^8.56.0",
            "eslint-config-next": "14.0.4",
            "postcss": "^8.4.32",
            "tailwindcss": "^3.4.0",
            "typescript": "^5.3.3"
          }
        }, null, 2)
      }
    },
    'tsconfig.json': {
      file: {
        contents: JSON.stringify({
          compilerOptions: {
            target: "es5",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [
              {
                name: "next"
              }
            ],
            paths: {
              "@/*": ["./*"]
            }
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"]
        }, null, 2)
      }
    },
    'next.config.js': {
      file: {
        contents: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}

module.exports = nextConfig`
      }
    },
    'tailwind.config.js': {
      file: {
        contents: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.5)' },
          '50%': { boxShadow: '0 0 40px rgba(99, 102, 241, 0.8)' },
        },
      },
    },
  },
  plugins: [],
}`
      }
    },
    'postcss.config.js': {
      file: {
        contents: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
      }
    },
    '.eslintrc.json': {
      file: {
        contents: JSON.stringify({
          extends: "next/core-web-vitals"
        }, null, 2)
      }
    },
    'app': {
      directory: {
        'layout.tsx': {
          file: {
            contents: `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ZapDev Next.js App',
  description: 'Built with Next.js, TypeScript, and Tailwind CSS',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`
          }
        },
        'page.tsx': {
          file: {
            contents: `'use client'

import { motion } from 'framer-motion'
import { Code2, Sparkles, Zap, Rocket } from 'lucide-react'
import { useState } from 'react'

export default function Home() {
  const [isHovered, setIsHovered] = useState(false)

  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-900 via-blue-900 to-blue-900">
      <div className="container mx-auto px-4 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
            className="inline-block mb-8"
          >
            <Code2 className="w-20 h-20 text-blue-400" />
          </motion.div>
          
          <h1 className="text-6xl font-bold text-white mb-4">
            Welcome to{' '}
            <span className="bg-gradient-to-r from-blue-400 to-blue-600 bg-clip-text text-transparent">
              ZapDev
            </span>
          </h1>
          
          <p className="text-xl text-gray-300 mb-8">
            Build amazing Next.js applications with E2B integration
          </p>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onHoverStart={() => setIsHovered(true)}
            onHoverEnd={() => setIsHovered(false)}
            className="relative px-8 py-4 bg-gradient-to-r from-blue-600 to-blue-600 text-white font-semibold rounded-lg shadow-lg hover:shadow-xl transition-all duration-300"
          >
            <span className="relative z-10 flex items-center gap-2">
              Get Started
              <motion.div
                animate={{ x: isHovered ? 5 : 0 }}
                transition={{ duration: 0.2 }}
              >
                <Rocket className="w-5 h-5" />
              </motion.div>
            </span>
            {isHovered && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="absolute inset-0 bg-gradient-to-r from-blue-700 to-blue-700 rounded-lg"
              />
            )}
          </motion.button>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-8 mt-16">
          {[
            {
              icon: <Zap className="w-8 h-8" />,
              title: "Lightning Fast",
              description: "Built on Next.js 14 with React Server Components for optimal performance"
            },
            {
              icon: <Sparkles className="w-8 h-8" />,
              title: "Beautiful Animations",
              description: "Smooth animations powered by Framer Motion for delightful user experiences"
            },
            {
              icon: <Code2 className="w-8 h-8" />,
              title: "E2B Integration",
              description: "Execute code in secure sandboxes with real-time feedback and results"
            }
          ].map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              whileHover={{ y: -5 }}
              className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20"
            >
              <motion.div
                whileHover={{ rotate: 360 }}
                transition={{ duration: 0.5 }}
                className="text-blue-400 mb-4"
              >
                {feature.icon}
              </motion.div>
              <h3 className="text-xl font-semibold text-white mb-2">
                {feature.title}
              </h3>
              <p className="text-gray-300">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </main>
  )
}`
          }
        },
        'globals.css': {
          file: {
            contents: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: 0 0% 3.9%;
  --foreground: 0 0% 98%;
  --primary: 262.1 83.3% 57.8%;
  --primary-foreground: 0 0% 98%;
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}

@layer utilities {
  .animate-pulse-glow {
    animation: pulseGlow 2s ease-in-out infinite;
  }
}`
          }
        }
      }
    },
    'components': {
      directory: {
        'Button.tsx': {
          file: {
            contents: `'use client'

import { motion } from 'framer-motion'
import { ReactNode } from 'react'
import { cn } from '@/lib/utils'

interface ButtonProps {
  children: ReactNode
  onClick?: () => void
  variant?: 'primary' | 'secondary' | 'outline'
  className?: string
}

export function Button({ children, onClick, variant = 'primary', className }: ButtonProps) {
  const variants = {
    primary: 'bg-gradient-to-r from-blue-600 to-blue-600 text-white hover:from-blue-700 hover:to-blue-700',
    secondary: 'bg-gray-700 text-white hover:bg-gray-600',
    outline: 'border-2 border-blue-600 text-blue-600 hover:bg-blue-600 hover:text-white'
  }

  return (
    <motion.button
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
      onClick={onClick}
      className={cn(
        'px-6 py-3 rounded-lg font-semibold transition-all duration-300 shadow-lg hover:shadow-xl',
        variants[variant],
        className
      )}
    >
      {children}
    </motion.button>
  )
}`
          }
        }
      }
    },
    'lib': {
      directory: {
        'utils.ts': {
          file: {
            contents: `import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}`
          }
        }
      }
    }
  }
});

export const createPortfolioTemplate = (): WebContainerTemplate => ({
  name: "Portfolio Template (TypeScript)",
  description: "A professional portfolio website with TypeScript and ESLint",
  files: {
    'package.json': {
      file: {
        contents: JSON.stringify({
          name: "zapdev-portfolio",
          version: "1.0.0",
          description: "Portfolio website generated by ZapDev",
          main: "dist/index.js",
          scripts: {
            start: "node dist/index.js",
            dev: "ts-node src/index.ts",
            build: "tsc",
            lint: "eslint src/**/*.ts",
            "lint:fix": "eslint src/**/*.ts --fix"
          },
          dependencies: {
            "express": "^4.18.2"
          },
          devDependencies: {
            "@types/express": "^4.17.17",
            "@types/node": "^20.0.0",
            "@typescript-eslint/eslint-plugin": "^6.0.0",
            "@typescript-eslint/parser": "^6.0.0",
            "eslint": "^8.44.0",
            "ts-node": "^10.9.1",
            "typescript": "^5.1.0"
          }
        }, null, 2)
      }
    },
    'tsconfig.json': {
      file: {
        contents: JSON.stringify({
          compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            outDir: "./dist",
            rootDir: "./src",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true
          },
          include: ["src/**/*"],
          exclude: ["node_modules", "dist"]
        }, null, 2)
      }
    },
    '.eslintrc.json': {
      file: {
        contents: JSON.stringify({
          parser: "@typescript-eslint/parser",
          extends: [
            "eslint:recommended",
            "@typescript-eslint/recommended"
          ],
          plugins: ["@typescript-eslint"],
          rules: {
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-unused-vars": "error",
            "prefer-const": "error"
          },
          env: {
            node: true,
            es2020: true
          }
        }, null, 2)
      }
    },
    'src': {
      directory: {
        'index.ts': {
          file: {
            contents: `import express from 'express';
import path from 'path';

const app = express();
const PORT = 3111;

app.use(express.static('public'));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(\`TypeScript Portfolio server running at http://localhost:\${PORT}\`);
});`
            }
          }
        }
      }
    },
    'public': {
      directory: {
        'index.html': {
          file: {
            contents: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>John Doe - Portfolio</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        
        header {
            background: white;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            position: fixed;
            width: 100%;
            top: 0;
            z-index: 1000;
        }
        
        nav {
            max-width: 1200px;
            margin: 0 auto;
            padding: 1rem 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .logo {
            font-size: 1.5rem;
            font-weight: bold;
            color: #333;
        }
        
        .nav-links {
            display: flex;
            gap: 2rem;
        }
        
        .nav-links a {
            text-decoration: none;
            color: #666;
            transition: color 0.3s;
        }
        
        .nav-links a:hover {
            color: #333;
        }
        
        .hero {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-align: center;
            padding: 150px 20px 100px;
            margin-top: 60px;
        }
        
        .profile-img {
            width: 120px;
            height: 120px;
            background: white;
            border-radius: 50%;
            margin: 0 auto 2rem;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 3rem;
        }
        
        .hero h1 {
            font-size: 3rem;
            margin-bottom: 1rem;
        }
        
        .hero p {
            font-size: 1.25rem;
            margin-bottom: 2rem;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }
        
        .btn {
            background: white;
            color: #667eea;
            padding: 12px 24px;
            border: none;
            border-radius: 5px;
            font-weight: 600;
            cursor: pointer;
            transition: transform 0.3s;
        }
        
        .btn:hover {
            transform: translateY(-2px);
        }
        
        section {
            padding: 80px 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        
        h2 {
            text-align: center;
            font-size: 2.5rem;
            margin-bottom: 3rem;
            color: #333;
        }
        
        .about-content {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 3rem;
            align-items: center;
        }
        
        .about-text {
            font-size: 1.1rem;
            color: #666;
            margin-bottom: 2rem;
        }
        
        .skills {
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
            margin-bottom: 2rem;
        }
        
        .skill-tag {
            background: #e3f2fd;
            color: #1976d2;
            padding: 0.5rem 1rem;
            border-radius: 20px;
            font-size: 0.9rem;
            font-weight: 500;
        }
        
        .quick-facts {
            background: white;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
            padding: 2rem;
        }
        
        .quick-facts h3 {
            margin-bottom: 1rem;
        }
        
        .quick-facts ul {
            list-style: none;
        }
        
        .quick-facts li {
            margin-bottom: 0.5rem;
            color: #666;
        }
        
        .projects {
            background: #f8f9fa;
        }
        
        .projects-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }
        
        .project-card {
            background: white;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
            overflow: hidden;
            transition: transform 0.3s;
        }
        
        .project-card:hover {
            transform: translateY(-5px);
        }
        
        .project-image {
            height: 200px;
            background: linear-gradient(45deg, #667eea, #764ba2);
        }
        
        .project-content {
            padding: 1.5rem;
        }
        
        .project-content h3 {
            margin-bottom: 0.5rem;
        }
        
        .project-content p {
            color: #666;
            margin-bottom: 1rem;
        }
        
        .project-tags {
            display: flex;
            gap: 0.5rem;
        }
        
        .project-tag {
            background: #e3f2fd;
            color: #1976d2;
            padding: 0.25rem 0.75rem;
            border-radius: 15px;
            font-size: 0.8rem;
        }
        
        .contact {
            background: #333;
            color: white;
            text-align: center;
        }
        
        .contact h2 {
            color: white;
        }
        
        .contact p {
            font-size: 1.25rem;
            margin-bottom: 2rem;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }
        
        .contact-buttons {
            display: flex;
            justify-content: center;
            gap: 1rem;
        }
        
        .btn-secondary {
            background: #667eea;
            color: white;
            padding: 12px 24px;
            border: none;
            border-radius: 5px;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.3s;
        }
        
        .btn-secondary:hover {
            background: #5a6fd8;
        }
        
        .btn-outline {
            background: transparent;
            color: white;
            border: 2px solid white;
            padding: 10px 22px;
            border-radius: 5px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
        }
        
        .btn-outline:hover {
            background: white;
            color: #333;
        }
        
        @media (max-width: 768px) {
            .about-content {
                grid-template-columns: 1fr;
            }
            
            .nav-links {
                display: none;
            }
            
            .hero h1 {
                font-size: 2rem;
            }
            
            .contact-buttons {
                flex-direction: column;
                align-items: center;
            }
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <div class="logo">John Doe</div>
            <div class="nav-links">
                <a href="#about">About</a>
                <a href="#projects">Projects</a>
                <a href="#contact">Contact</a>
            </div>
        </nav>
    </header>

    <section class="hero">
        <div class="container">
            <div class="profile-img">👨‍💻</div>
            <h1>Full Stack Developer</h1>
            <p>Passionate about creating beautiful, functional web applications that solve real-world problems</p>
            <button class="btn">View My Work</button>
        </div>
    </section>

    <section id="about">
        <div class="container">
            <h2>About Me</h2>
            <div class="about-content">
                <div>
                    <p class="about-text">
                        I'm a passionate full-stack developer with 5+ years of experience building web applications. 
                        I love working with modern technologies and solving complex problems.
                    </p>
                    <h3>Skills</h3>
                    <div class="skills">
                        <span class="skill-tag">TypeScript</span>
                        <span class="skill-tag">React</span>
                        <span class="skill-tag">Node.js</span>
                        <span class="skill-tag">Express</span>
                        <span class="skill-tag">PostgreSQL</span>
                        <span class="skill-tag">AWS</span>
                    </div>
                </div>
                <div class="quick-facts">
                    <h3>Quick Facts</h3>
                    <ul>
                        <li>📍 Based in San Francisco, CA</li>
                        <li>🎓 Computer Science Degree</li>
                        <li>💼 5+ Years Experience</li>
                        <li>🏆 10+ Projects Completed</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="projects" class="projects">
        <div class="container">
            <h2>My Projects</h2>
            <div class="projects-grid">
                <div class="project-card">
                    <div class="project-image"></div>
                    <div class="project-content">
                        <h3>E-commerce Platform</h3>
                        <p>A full-featured online store with payment processing and inventory management.</p>
                        <div class="project-tags">
                            <span class="project-tag">React</span>
                            <span class="project-tag">Node.js</span>
                        </div>
                    </div>
                </div>
                <div class="project-card">
                    <div class="project-image"></div>
                    <div class="project-content">
                        <h3>Task Management App</h3>
                        <p>A collaborative task management tool with real-time updates and team features.</p>
                        <div class="project-tags">
                            <span class="project-tag">Vue.js</span>
                            <span class="project-tag">Socket.io</span>
                        </div>
                    </div>
                </div>
                <div class="project-card">
                    <div class="project-image"></div>
                    <div class="project-content">
                        <h3>Weather Dashboard</h3>
                        <p>A beautiful weather app with location-based forecasts and detailed analytics.</p>
                        <div class="project-tags">
                            <span class="project-tag">React</span>
                            <span class="project-tag">Chart.js</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="contact">
        <div class="container">
            <h2>Let's Work Together</h2>
            <p>I'm always open to discussing new opportunities and interesting projects</p>
            <div class="contact-buttons">
                <button class="btn-secondary">Email Me</button>
                <button class="btn-outline">Download Resume</button>
            </div>
        </div>
    </section>
</body>
</html>`
          }
        }
      }
    }
  }
});

export const templates = {
  nextjs: createNextJsTemplate,
  basic: createBasicExpressTemplate,
  landing: createLandingPageTemplate,
  portfolio: createPortfolioTemplate,
};

export type TemplateKey = keyof typeof templates;