// Next.js project templates for WebContainer

export interface NextJSTemplate {
  name: string;
  description: string;
  files: Record<string, { file: { contents: string } } | { directory: Record<string, unknown> }>;
}

export const createBasicNextJSTemplate = (): NextJSTemplate => ({
  name: "Basic Next.js App",
  description: "A simple Next.js application with TypeScript and Tailwind CSS",
  files: {
    'package.json': {
      file: {
        contents: JSON.stringify({
          name: "zapdev-nextjs-app",
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build", 
            start: "next start",
            lint: "next lint"
          },
          dependencies: {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "next": "^14.1.0",
            "@types/node": "^20.11.0",
            "@types/react": "^18.2.48",
            "@types/react-dom": "^18.2.18",
            "typescript": "^5.3.3",
            "tailwindcss": "^3.4.1",
            "autoprefixer": "^10.4.17", 
            "postcss": "^8.4.35",
            "clsx": "^2.1.0",
            "lucide-react": "^0.323.0"
          }
        }, null, 2)
      }
    },
    'next.config.js': {
      file: {
        contents: `/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig`
      }
    },
    'tsconfig.json': {
      file: {
        contents: JSON.stringify({
          compilerOptions: {
            target: "es5",
            lib: ["dom", "dom.iterable", "es6"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }],
            baseUrl: ".",
            paths: { "@/*": ["./src/*"] }
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"]
        }, null, 2)
      }
    },
    'tailwind.config.js': {
      file: {
        contents: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
      }
    },
    'postcss.config.js': {
      file: {
        contents: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
      }
    },
    'src': {
      directory: {
        'app': {
          directory: {
            'globals.css': {
              file: {
                contents: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`
              }
            },
            'layout.tsx': {
              file: {
                contents: `import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ZapDev App',
  description: 'Generated by ZapDev AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`
              }
            },
            'page.tsx': {
              file: {
                contents: `export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="container mx-auto px-4 py-16">
        <div className="text-center">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Welcome to Your Next.js App
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Built with Next.js, TypeScript, and Tailwind CSS
          </p>
          <div className="bg-white rounded-lg shadow-xl p-8 max-w-2xl mx-auto">
            <p className="text-lg text-gray-700">
              Your application is ready! Start building amazing features.
            </p>
          </div>
        </div>
      </div>
    </main>
  )
}`
              }
            }
          }
        },
        'components': {
          directory: {
            'ui': { directory: {} }
          }
        }
      }
    }
  }
});

export const createLandingPageTemplate = (): NextJSTemplate => ({
  name: "Landing Page Template",
  description: "A modern landing page with hero section, features, and CTA",
  files: {
    ...createBasicNextJSTemplate().files,
    'src': {
      directory: {
        'app': {
          directory: {
            'globals.css': {
              file: {
                contents: `@tailwind base;
@tailwind components;
@tailwind utilities;

.hero-gradient {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.feature-card {
  @apply bg-white rounded-lg shadow-lg p-6 transition-transform hover:scale-105;
}`
              }
            },
            'layout.tsx': {
              file: {
                contents: `import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ZapDev Landing Page',
  description: 'Beautiful landing page created with ZapDev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`
              }
            },
            'page.tsx': {
              file: {
                contents: `export default function LandingPage() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="hero-gradient py-20">
        <div className="container mx-auto px-4 text-center text-white">
          <h1 className="text-5xl md:text-6xl font-bold mb-6">
            Welcome to the Future
          </h1>
          <p className="text-xl md:text-2xl mb-8 max-w-2xl mx-auto">
            Experience the next generation of web applications built with cutting-edge technology
          </p>
          <button className="bg-white text-purple-600 px-8 py-3 rounded-full font-semibold text-lg hover:bg-gray-100 transition-colors">
            Get Started Today
          </button>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <h2 className="text-4xl font-bold text-center mb-16 text-gray-800">
            Amazing Features
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="feature-card">
              <div className="w-12 h-12 bg-blue-500 rounded-lg mb-4 flex items-center justify-center">
                <span className="text-white text-2xl">⚡</span>
              </div>
              <h3 className="text-xl font-semibold mb-2">Lightning Fast</h3>
              <p className="text-gray-600">Built with Next.js for optimal performance and speed</p>
            </div>
            <div className="feature-card">
              <div className="w-12 h-12 bg-green-500 rounded-lg mb-4 flex items-center justify-center">
                <span className="text-white text-2xl">🎨</span>
              </div>
              <h3 className="text-xl font-semibold mb-2">Beautiful Design</h3>
              <p className="text-gray-600">Carefully crafted with attention to every detail</p>
            </div>
            <div className="feature-card">
              <div className="w-12 h-12 bg-purple-500 rounded-lg mb-4 flex items-center justify-center">
                <span className="text-white text-2xl">🚀</span>
              </div>
              <h3 className="text-xl font-semibold mb-2">Easy to Deploy</h3>
              <p className="text-gray-600">Deploy anywhere with our optimized build process</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gray-900 text-white">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-4xl font-bold mb-6">Ready to Get Started?</h2>
          <p className="text-xl mb-8 max-w-2xl mx-auto">
            Join thousands of users who are already building amazing things
          </p>
          <button className="bg-blue-600 text-white px-8 py-3 rounded-full font-semibold text-lg hover:bg-blue-700 transition-colors">
            Start Building Now
          </button>
        </div>
      </section>
    </div>
  )
}`
              }
            }
          }
        },
        'components': {
          directory: {
            'ui': { directory: {} }
          }
        }
      }
    }
  }
});

export const createPortfolioTemplate = (): NextJSTemplate => ({
  name: "Portfolio Template",
  description: "A professional portfolio website template",
  files: {
    ...createBasicNextJSTemplate().files,
    'src': {
      directory: {
        'app': {
          directory: {
            'globals.css': {
              file: {
                contents: `@tailwind base;
@tailwind components;
@tailwind utilities;

.project-card {
  @apply bg-white rounded-lg shadow-lg overflow-hidden transition-transform hover:scale-105;
}

.skill-badge {
  @apply px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm font-medium;
}`
              }
            },
            'layout.tsx': {
              file: {
                contents: `import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio - ZapDev',
  description: 'Professional portfolio created with ZapDev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`
              }
            },
            'page.tsx': {
              file: {
                contents: `export default function Portfolio() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="container mx-auto px-4 py-6">
          <nav className="flex justify-between items-center">
            <h1 className="text-2xl font-bold text-gray-800">John Doe</h1>
            <div className="space-x-6">
              <a href="#about" className="text-gray-600 hover:text-gray-800">About</a>
              <a href="#projects" className="text-gray-600 hover:text-gray-800">Projects</a>
              <a href="#contact" className="text-gray-600 hover:text-gray-800">Contact</a>
            </div>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-purple-600 text-white">
        <div className="container mx-auto px-4 text-center">
          <div className="w-32 h-32 bg-white rounded-full mx-auto mb-6 flex items-center justify-center">
            <span className="text-4xl">👨‍💻</span>
          </div>
          <h1 className="text-5xl font-bold mb-4">Full Stack Developer</h1>
          <p className="text-xl mb-8 max-w-2xl mx-auto">
            Passionate about creating beautiful, functional web applications that solve real-world problems
          </p>
          <button className="bg-white text-blue-600 px-6 py-3 rounded-lg font-semibold hover:bg-gray-100 transition-colors">
            View My Work
          </button>
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-4xl font-bold text-center mb-16 text-gray-800">About Me</h2>
          <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-12 items-center">
            <div>
              <p className="text-lg text-gray-600 mb-6">
                I'm a passionate full-stack developer with 5+ years of experience building web applications. 
                I love working with modern technologies and solving complex problems.
              </p>
              <div className="space-y-2">
                <h3 className="text-xl font-semibold mb-4">Skills</h3>
                <div className="flex flex-wrap gap-2">
                  <span className="skill-badge">React</span>
                  <span className="skill-badge">Next.js</span>
                  <span className="skill-badge">TypeScript</span>
                  <span className="skill-badge">Node.js</span>
                  <span className="skill-badge">PostgreSQL</span>
                  <span className="skill-badge">AWS</span>
                </div>
              </div>
            </div>
            <div className="bg-white rounded-lg shadow-lg p-8">
              <h3 className="text-xl font-semibold mb-4">Quick Facts</h3>
              <ul className="space-y-2 text-gray-600">
                <li>📍 Based in San Francisco, CA</li>
                <li>🎓 Computer Science Degree</li>
                <li>💼 5+ Years Experience</li>
                <li>🏆 10+ Projects Completed</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Projects Section */}
      <section id="projects" className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <h2 className="text-4xl font-bold text-center mb-16 text-gray-800">My Projects</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="project-card">
              <div className="h-48 bg-gradient-to-r from-blue-400 to-purple-500"></div>
              <div className="p-6">
                <h3 className="text-xl font-semibold mb-2">E-commerce Platform</h3>
                <p className="text-gray-600 mb-4">A full-featured online store built with Next.js and Stripe integration.</p>
                <div className="flex space-x-2">
                  <span className="skill-badge">Next.js</span>
                  <span className="skill-badge">Stripe</span>
                </div>
              </div>
            </div>
            <div className="project-card">
              <div className="h-48 bg-gradient-to-r from-green-400 to-blue-500"></div>
              <div className="p-6">
                <h3 className="text-xl font-semibold mb-2">Task Management App</h3>
                <p className="text-gray-600 mb-4">A collaborative task management tool with real-time updates.</p>
                <div className="flex space-x-2">
                  <span className="skill-badge">React</span>
                  <span className="skill-badge">Socket.io</span>
                </div>
              </div>
            </div>
            <div className="project-card">
              <div className="h-48 bg-gradient-to-r from-purple-400 to-pink-500"></div>
              <div className="p-6">
                <h3 className="text-xl font-semibold mb-2">Weather Dashboard</h3>
                <p className="text-gray-600 mb-4">A beautiful weather app with location-based forecasts and analytics.</p>
                <div className="flex space-x-2">
                  <span className="skill-badge">Vue.js</span>
                  <span className="skill-badge">Chart.js</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="py-20 bg-gray-900 text-white">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-4xl font-bold mb-8">Let's Work Together</h2>
          <p className="text-xl mb-8 max-w-2xl mx-auto">
            I'm always open to discussing new opportunities and interesting projects
          </p>
          <div className="flex justify-center space-x-6">
            <button className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors">
              Email Me
            </button>
            <button className="bg-gray-700 text-white px-6 py-3 rounded-lg hover:bg-gray-600 transition-colors">
              Download Resume
            </button>
          </div>
        </div>
      </section>
    </div>
  )
}`
              }
            }
          }
        },
        'components': {
          directory: {
            'ui': { directory: {} }
          }
        }
      }
    }
  }
});

export const templates = {
  basic: createBasicNextJSTemplate,
  landing: createLandingPageTemplate,
  portfolio: createPortfolioTemplate,
};

export type TemplateKey = keyof typeof templates;