"use client";

import Link from "next/link";
import { useQuery } from "convex/react";

import { api } from "@/convex/_generated/api";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const statusVariants: Record<string, string> = {
  DRAFT: "bg-muted text-muted-foreground",
  OPEN: "bg-blue-500/20 text-blue-600 dark:text-blue-300",
  MERGED: "bg-emerald-500/20 text-emerald-600 dark:text-emerald-300",
  CLOSED: "bg-red-500/20 text-red-600 dark:text-red-300",
};

type PullRequestListProps = {
  repoFullName: string | null;
};

export function PullRequestList({ repoFullName }: PullRequestListProps) {
  const pullRequests = useQuery(
    api.github.listPullRequests,
    repoFullName ? { repoFullName, limit: 10 } : { limit: 10 }
  );

  return (
    <Card className="p-6 space-y-4">
      <div>
        <h3 className="text-lg font-semibold">Autonomous PRs</h3>
        <p className="text-sm text-muted-foreground">
          Latest branches generated by the 10x SWE agent
        </p>
      </div>

      {!pullRequests?.length && (
        <p className="text-sm text-muted-foreground">
          No pull requests recorded yet. Queue an issue to create the first PR.
        </p>
      )}

      <div className="space-y-3">
        {pullRequests?.map((pr) => (
          <div key={pr._id} className="border rounded-lg p-3 space-y-2">
            <div className="flex items-center justify-between gap-2">
              <p className="font-medium line-clamp-2">{pr.title}</p>
              <Badge className={statusVariants[pr.status] ?? ""}>{pr.status.toLowerCase()}</Badge>
            </div>
            <p className="text-xs text-muted-foreground">
              Branch {pr.branchName} • #{pr.prNumber ?? "pending"}
            </p>
            {pr.prUrl && (
              <Link
                href={pr.prUrl}
                target="_blank"
                rel="noreferrer"
                className="text-sm text-primary hover:underline inline-flex items-center gap-1"
              >
                View on GitHub →
              </Link>
            )}
          </div>
        ))}
      </div>
    </Card>
  );
}
