'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';

interface TosPrivacyDialogProps {
  type: 'tos' | 'privacy';
  children: React.ReactNode;
}

const TOS_CONTENT = `
**TERMS OF SERVICE**

*Last updated: ${new Date().toLocaleDateString()}*

**1. ACCEPTANCE OF TERMS**

By accessing and using ZapDev ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.

**2. DESCRIPTION OF SERVICE**

ZapDev is an AI-powered development platform that enables users to generate, preview, and deploy applications using artificial intelligence models. The Service includes code generation, live preview capabilities, and deployment tools.

**3. USER ACCOUNTS AND REGISTRATION**

3.1. You must provide accurate and complete registration information.
3.2. You are responsible for maintaining the confidentiality of your account credentials.
3.3. You are responsible for all activities that occur under your account.
3.4. You must notify us immediately of any unauthorized use of your account.

**4. ACCEPTABLE USE POLICY**

You agree not to:
- Use the Service for any illegal or unauthorized purpose
- Generate malicious code or content that could harm users or systems
- Violate any laws in your jurisdiction
- Infringe upon intellectual property rights of others
- Attempt to gain unauthorized access to our systems
- Use the Service to spam, harass, or abuse others

**5. INTELLECTUAL PROPERTY RIGHTS**

5.1. **Your Content**: You retain ownership of code and content you create using our Service.
5.2. **Generated Code**: Code generated by AI models is provided "as-is" and you are responsible for ensuring it meets your requirements and doesn't infringe on third-party rights.
5.3. **Our Platform**: ZapDev and its underlying technology remain our intellectual property.

**6. AI-GENERATED CONTENT DISCLAIMER**

6.1. AI-generated code is provided for informational and development purposes only.
6.2. We do not guarantee the accuracy, completeness, or functionality of AI-generated code.
6.3. You are responsible for reviewing, testing, and validating all generated content.
6.4. Use of AI-generated code in production environments is at your own risk.

**7. PRIVACY AND DATA PROTECTION**

Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our Service.

**8. LIMITATION OF LIABILITY**

TO THE MAXIMUM EXTENT PERMITTED BY LAW, ZAPDEV SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR OTHER INTANGIBLE LOSSES.

**9. SERVICE AVAILABILITY**

9.1. We strive to maintain high availability but do not guarantee uninterrupted service.
9.2. We may suspend or terminate the Service for maintenance or other operational reasons.
9.3. We reserve the right to modify or discontinue features with reasonable notice.

**10. SUBSCRIPTION AND BILLING**

10.1. Paid plans are billed according to the pricing displayed at the time of purchase.
10.2. Subscriptions automatically renew unless cancelled.
10.3. Refunds are provided according to our refund policy.

**11. TERMINATION**

11.1. You may terminate your account at any time.
11.2. We may terminate or suspend accounts that violate these terms.
11.3. Upon termination, your right to use the Service ceases immediately.

**12. MODIFICATIONS TO TERMS**

We reserve the right to modify these terms at any time. We will notify users of significant changes via email or platform notifications.

**13. GOVERNING LAW**

These terms are governed by the laws of The United States Of America, without regard to conflict of law provisions.

**14. CONTACT INFORMATION**

For questions about these Terms of Service, please contact us at: legal@zapdev.ai

By using ZapDev, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
`;

const PRIVACY_POLICY_CONTENT = `
**PRIVACY POLICY**

*Last updated: ${new Date().toLocaleDateString()}*

**1. INTRODUCTION**

ZapDev ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI-powered development platform.

**2. INFORMATION WE COLLECT**

**2.1. Information You Provide Directly:**
- Account registration information (name, email address)
- Profile information you choose to provide
- Code and content you create or upload
- Communications with our support team

**2.2. Information Collected Automatically:**
- Usage data and analytics
- Device and browser information
- IP addresses and location data
- Cookies and similar tracking technologies

**2.3. Information from Third Parties:**
- OAuth provider information (GitHub, Google) when you choose to authenticate
- Analytics and performance monitoring data

**3. HOW WE USE YOUR INFORMATION**

We use your information to:
- Provide and improve our services
- Process your requests and transactions
- Send important service updates and notifications
- Provide customer support
- Analyze usage patterns to enhance user experience
- Ensure platform security and prevent abuse
- Comply with legal obligations

**4. AI MODEL TRAINING AND CODE PROCESSING**

**4.1. Code Privacy Commitment:**
- We do NOT train our AI models on your private code or projects
- Your code is processed only to provide the requested services
- Code generation requests are sent to third-party AI providers with privacy protections

**4.2. Data Hosting:**
- All services are hosted in secure data centers in the United States
- We use industry-standard encryption and security measures
- Access to your data is strictly limited to authorized personnel

**5. INFORMATION SHARING AND DISCLOSURE**

We do not sell your personal information. We may share your information only in these limited circumstances:

**5.1. With Your Consent:** When you explicitly authorize us to share specific information.

**5.2. Service Providers:** With trusted third-party providers who assist in operating our platform (hosting, analytics, payment processing) under strict confidentiality agreements.

**5.3. AI Service Providers:** Code generation requests may be sent to third-party AI providers (OpenAI, Anthropic, etc.) with privacy protections in place.

**5.4. Legal Requirements:** When required by law, court order, or to protect our rights and safety.

**5.5. Business Transfers:** In connection with mergers, acquisitions, or asset sales, with appropriate privacy protections.

**6. DATA RETENTION**

- Account information: Retained while your account is active and for a reasonable period after deletion
- Usage logs: Typically retained for 12 months for security and analytics purposes
- Code and projects: Retained according to your account settings and deletion requests

**7. YOUR PRIVACY RIGHTS**

Depending on your location, you may have the following rights:
- Access your personal information
- Correct inaccurate information
- Delete your personal information
- Export your data
- Opt-out of certain data processing
- Withdraw consent where applicable

To exercise these rights, contact us at privacy@zapdev.ai.

**8. SECURITY MEASURES**

We implement comprehensive security measures including:
- Encryption in transit and at rest
- Regular security audits and monitoring
- Access controls and authentication requirements
- Incident response procedures
- Regular security training for our team

**9. COOKIES AND TRACKING TECHNOLOGIES**

We use cookies and similar technologies to:
- Maintain your login session
- Remember your preferences
- Analyze usage patterns
- Improve our services

You can control cookie settings through your browser preferences.

**10. THIRD-PARTY SERVICES**

Our platform integrates with third-party services (GitHub, Google, payment processors). Please review their privacy policies as they govern their data practices.

**11. INTERNATIONAL DATA TRANSFERS**

If you access our service from outside the United States, your information may be transferred to and processed in the US. We ensure appropriate safeguards are in place for such transfers.

**12. CHILDREN'S PRIVACY**

Our service is not intended for children under 13. We do not knowingly collect personal information from children under 13. If you believe we have collected such information, please contact us immediately.

**13. CALIFORNIA PRIVACY RIGHTS**

California residents have additional rights under the CCPA, including the right to know what personal information is collected and how it's used. Contact us for more information about exercising these rights.

**14. CHANGES TO THIS PRIVACY POLICY**

We may update this Privacy Policy periodically. We will notify you of significant changes via email or platform notifications. Your continued use constitutes acceptance of the updated policy.

**15. CONTACT INFORMATION**

For privacy-related questions or to exercise your rights, contact us at:
- Email: business.zapdev@proton.me

We are committed to protecting your privacy and will respond to your inquiries promptly.
`;

export function TosPrivacyDialog({ type, children }: TosPrivacyDialogProps) {
  const content =
    type === 'tos'
      ? {
          title: 'Terms of Service',
          content: TOS_CONTENT,
        }
      : {
          title: 'Privacy Policy',
          content: PRIVACY_POLICY_CONTENT,
        };

  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-h-[80vh] sm:max-w-4xl">
        <DialogHeader>
          <DialogTitle className="text-xl font-semibold">{content.title}</DialogTitle>
        </DialogHeader>
        <ScrollArea className="mt-4 h-[60vh] pr-4">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <div className="whitespace-pre-line text-sm leading-6">{content.content}</div>
          </div>
        </ScrollArea>
        <div className="mt-4 flex justify-end border-t pt-4">
          <Button variant="outline" className="text-sm">
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
