import { motion } from "framer-motion";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-black text-foreground">
      <Navigation />
      
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="prose prose-invert max-w-none"
        >
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent mb-4">
              Terms of Service
            </h1>
            <p className="text-gray-400 text-lg">Last updated: 7/18/2025</p>
          </div>

          <div className="space-y-8 text-gray-300 leading-relaxed">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">1. ACCEPTANCE OF TERMS</h2>
              <p>
                By accessing and using ZapDev ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">2. DESCRIPTION OF SERVICE</h2>
              <p>
                ZapDev is an AI-powered development platform that enables users to generate, preview, and deploy applications using artificial intelligence models. The Service includes code generation, live preview capabilities, and deployment tools.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">3. USER ACCOUNTS AND REGISTRATION</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>You must provide accurate and complete registration information.</li>
                <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
                <li>You are responsible for all activities that occur under your account.</li>
                <li>You must notify us immediately of any unauthorized use of your account.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">4. ACCEPTABLE USE POLICY</h2>
              <p className="mb-3">You agree not to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Use the Service for any illegal or unauthorized purpose</li>
                <li>Generate malicious code or content that could harm users or systems</li>
                <li>Violate any laws in your jurisdiction</li>
                <li>Infringe upon intellectual property rights of others</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Use the Service to spam, harass, or abuse others</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">5. INTELLECTUAL PROPERTY RIGHTS</h2>
              <div className="space-y-3">
                <div>
                  <h3 className="text-lg font-medium text-white">5.1. Your Content:</h3>
                  <p>You retain ownership of code and content you create using our Service.</p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white">5.2. Generated Code:</h3>
                  <p>Code generated by AI models is provided "as-is" and you are responsible for ensuring it meets your requirements and doesn't infringe on third-party rights.</p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white">5.3. Our Platform:</h3>
                  <p>ZapDev and its underlying technology remain our intellectual property.</p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">6. AI-GENERATED CONTENT DISCLAIMER</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI-generated code is provided for informational and development purposes only.</li>
                <li>We do not guarantee the accuracy, completeness, or functionality of AI-generated code.</li>
                <li>You are responsible for reviewing, testing, and validating all generated content.</li>
                <li>Use of AI-generated code in production environments is at your own risk.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">7. PRIVACY AND DATA PROTECTION</h2>
              <p>
                Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">8. LIMITATION OF LIABILITY</h2>
              <p className="uppercase">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, ZAPDEV SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR OTHER INTANGIBLE LOSSES.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">9. SERVICE AVAILABILITY</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>We strive to maintain high availability but do not guarantee uninterrupted service.</li>
                <li>We may suspend or terminate the Service for maintenance or other operational reasons.</li>
                <li>We reserve the right to modify or discontinue features with reasonable notice.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">10. SUBSCRIPTION AND BILLING</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>Paid plans are billed according to the pricing displayed at the time of purchase.</li>
                <li>Subscriptions automatically renew unless cancelled.</li>
                <li>Refunds are provided according to our refund policy.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">11. TERMINATION</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>You may terminate your account at any time.</li>
                <li>We may terminate or suspend accounts that violate these terms.</li>
                <li>Upon termination, your right to use the Service ceases immediately.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">12. MODIFICATIONS TO TERMS</h2>
              <p>
                We reserve the right to modify these terms at any time. We will notify users of significant changes via email or platform notifications.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">13. GOVERNING LAW</h2>
              <p>
                These terms are governed by the laws of The United States Of America, without regard to conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">14. CONTACT INFORMATION</h2>
              <p>
                For questions about these Terms of Service, please contact us at:{" "}
                <a href="mailto:support@zapdev.link" className="text-purple-400 hover:text-purple-300 transition-colors">
                  support@zapdev.link
                </a>
              </p>
            </section>

            <div className="border-t border-gray-700 pt-8 mt-12">
              <p className="text-center text-gray-400">
                By using ZapDev, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
              </p>
            </div>
          </div>
        </motion.div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsOfService; 