# This is a config for E2B sandbox template.
# You can use template ID (uf2u4ra0890yzo2cebs1) or template name (zapdev-react) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("zapdev-react") # Sync sandbox
# sandbox = await AsyncSandbox.create("zapdev-react") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zapdev-react')

team_id = "1db440ba-8980-4fca-b8f5-46375679ee47"
dockerfile = "e2b.Dockerfile"
template_name = "zapdev-react"
template_id = "uf2u4ra0890yzo2cebs1"
