# This is a config for E2B sandbox template.
# You can use template ID (cvd2h1uz3b4a48g36ead) or template name (zapdev-svelte) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("zapdev-svelte") # Sync sandbox
# sandbox = await AsyncSandbox.create("zapdev-svelte") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zapdev-svelte')

team_id = "1db440ba-8980-4fca-b8f5-46375679ee47"
dockerfile = "e2b.Dockerfile"
template_name = "zapdev-svelte"
template_id = "cvd2h1uz3b4a48g36ead"
