name: PR Size Labels

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/xs"
          s_label: "size/s"
          m_label: "size/m"
          l_label: "size/l"
          xl_label: "size/xl"
          xxl_label: "size/xxl"
          xs_max_size: "10"
          s_max_size: "50"
          m_max_size: "200"
          l_max_size: "500"
          xl_max_size: "1000"
